<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\BLL\UsuarioBLL' shared autowired service.

include_once $this->targetDirs[3].'\\src\\BLL\\BaseBLL.php';
include_once $this->targetDirs[3].'\\src\\BLL\\UsuarioBLL.php';

$this->privates['App\BLL\UsuarioBLL'] = $instance = new \App\BLL\UsuarioBLL(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['validator'] ?? $this->getValidatorService()), ($this->services['security.token_storage'] ?? $this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage()));

$instance->setEncoder(($this->services['security.password_encoder'] ?? $this->load(__DIR__.'/getSecurity_PasswordEncoderService.php')));
$instance->setJWTManager(($this->privates['lexik_jwt_authentication.jwt_manager'] ?? $this->load(__DIR__.'/getLexikJwtAuthentication_JwtManagerService.php')));

return $instance;
