<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\EntradaController:buyTickets' => function () {
    return ($this->privates['service_locator.pcinoB2'] ?? $this->load(__DIR__.'/getServiceLocator_PcinoB2Service.php'));
}, 'App\\Controller\\EntradaController:showTickets' => function () {
    return ($this->privates['service_locator.1hqTzKz'] ?? $this->load(__DIR__.'/getServiceLocator_1hqTzKzService.php'));
}, 'App\\Controller\\EventoController:eliminarEvento' => function () {
    return ($this->privates['service_locator.6v4OAC7'] ?? $this->load(__DIR__.'/getServiceLocator_6v4OAC7Service.php'));
}, 'App\\Controller\\EventoController:nuevoFormEvento' => function () {
    return ($this->privates['service_locator.6IJdv80'] ?? $this->load(__DIR__.'/getServiceLocator_6IJdv80Service.php'));
}, 'App\\Controller\\EventoController:showEventDetails' => function () {
    return ($this->privates['service_locator.6v4OAC7'] ?? $this->load(__DIR__.'/getServiceLocator_6v4OAC7Service.php'));
}, 'App\\Controller\\EventoController:showEventsIndex' => function () {
    return ($this->privates['service_locator.6v4OAC7'] ?? $this->load(__DIR__.'/getServiceLocator_6v4OAC7Service.php'));
}, 'App\\Controller\\EventoController:showMyEvents' => function () {
    return ($this->privates['service_locator.6IJdv80'] ?? $this->load(__DIR__.'/getServiceLocator_6IJdv80Service.php'));
}, 'App\\Controller\\SecurityController:login' => function () {
    return ($this->privates['service_locator.KELS8pk'] ?? $this->load(__DIR__.'/getServiceLocator_KELS8pkService.php'));
}, 'App\\Controller\\SecurityController:nuevoFormUsuario' => function () {
    return ($this->privates['service_locator.l13HVKj'] ?? $this->load(__DIR__.'/getServiceLocator_L13HVKjService.php'));
}, 'App\\Controller\\UsuarioController:deleteUser' => function () {
    return ($this->privates['service_locator.ddNYmPk'] ?? $this->load(__DIR__.'/getServiceLocator_DdNYmPkService.php'));
}, 'App\\Controller\\UsuarioController:listarUsuarios' => function () {
    return ($this->privates['service_locator.brPeRy0'] ?? $this->load(__DIR__.'/getServiceLocator_BrPeRy0Service.php'));
}, 'App\\Controller\\UsuarioController:perfil' => function () {
    return ($this->privates['service_locator.rM_JHoH'] ?? $this->load(__DIR__.'/getServiceLocator_RMJHoHService.php'));
}, 'App\\Controller\\UsuarioController:updateUser' => function () {
    return ($this->privates['service_locator.brPeRy0'] ?? $this->load(__DIR__.'/getServiceLocator_BrPeRy0Service.php'));
}, 'App\\Controller\\EntradaController::buyTickets' => function () {
    return ($this->privates['service_locator.pcinoB2'] ?? $this->load(__DIR__.'/getServiceLocator_PcinoB2Service.php'));
}, 'App\\Controller\\EntradaController::showTickets' => function () {
    return ($this->privates['service_locator.1hqTzKz'] ?? $this->load(__DIR__.'/getServiceLocator_1hqTzKzService.php'));
}, 'App\\Controller\\EventoController::eliminarEvento' => function () {
    return ($this->privates['service_locator.6v4OAC7'] ?? $this->load(__DIR__.'/getServiceLocator_6v4OAC7Service.php'));
}, 'App\\Controller\\EventoController::nuevoFormEvento' => function () {
    return ($this->privates['service_locator.6IJdv80'] ?? $this->load(__DIR__.'/getServiceLocator_6IJdv80Service.php'));
}, 'App\\Controller\\EventoController::showEventDetails' => function () {
    return ($this->privates['service_locator.6v4OAC7'] ?? $this->load(__DIR__.'/getServiceLocator_6v4OAC7Service.php'));
}, 'App\\Controller\\EventoController::showEventsIndex' => function () {
    return ($this->privates['service_locator.6v4OAC7'] ?? $this->load(__DIR__.'/getServiceLocator_6v4OAC7Service.php'));
}, 'App\\Controller\\EventoController::showMyEvents' => function () {
    return ($this->privates['service_locator.6IJdv80'] ?? $this->load(__DIR__.'/getServiceLocator_6IJdv80Service.php'));
}, 'App\\Controller\\SecurityController::login' => function () {
    return ($this->privates['service_locator.KELS8pk'] ?? $this->load(__DIR__.'/getServiceLocator_KELS8pkService.php'));
}, 'App\\Controller\\SecurityController::nuevoFormUsuario' => function () {
    return ($this->privates['service_locator.l13HVKj'] ?? $this->load(__DIR__.'/getServiceLocator_L13HVKjService.php'));
}, 'App\\Controller\\UsuarioController::deleteUser' => function () {
    return ($this->privates['service_locator.ddNYmPk'] ?? $this->load(__DIR__.'/getServiceLocator_DdNYmPkService.php'));
}, 'App\\Controller\\UsuarioController::listarUsuarios' => function () {
    return ($this->privates['service_locator.brPeRy0'] ?? $this->load(__DIR__.'/getServiceLocator_BrPeRy0Service.php'));
}, 'App\\Controller\\UsuarioController::perfil' => function () {
    return ($this->privates['service_locator.rM_JHoH'] ?? $this->load(__DIR__.'/getServiceLocator_RMJHoHService.php'));
}, 'App\\Controller\\UsuarioController::updateUser' => function () {
    return ($this->privates['service_locator.brPeRy0'] ?? $this->load(__DIR__.'/getServiceLocator_BrPeRy0Service.php'));
})));
