<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.1hqTzKz' shared service.

return $this->privates['service_locator.1hqTzKz'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('entradaBLL' => function (): ?\App\BLL\EntradaBLL {
    return ($this->privates['App\BLL\EntradaBLL'] ?? $this->load(__DIR__.'/getEntradaBLLService.php'));
}));
