<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.l13HVKj' shared service.

return $this->privates['service_locator.l13HVKj'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('encoder' => function () {
    return ($this->services['security.password_encoder'] ?? $this->load(__DIR__.'/getSecurity_PasswordEncoderService.php'));
}, 'usuarioBLL' => function (): ?\App\BLL\UsuarioBLL {
    return ($this->privates['App\BLL\UsuarioBLL'] ?? $this->load(__DIR__.'/getUsuarioBLLService.php'));
}));
