<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.LcyWu6e' shared service.

return $this->privates['service_locator.LcyWu6e'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('eventoBLL' => function (): ?\App\BLL\EventoBLL {
    return ($this->privates['App\BLL\EventoBLL'] ?? $this->load(__DIR__.'/getEventoBLLService.php'));
}));
