<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.request_matcher.CoBPJCB' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-foundation\\RequestMatcherInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-foundation\\RequestMatcher.php';

return $this->privates['security.request_matcher.CoBPJCB'] = new \Symfony\Component\HttpFoundation\RequestMatcher('^/api/v1/auth/login');
