<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNs2Dboa\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNs2Dboa/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNs2Dboa.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerNs2Dboa\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerNs2Dboa\srcProdProjectContainer(array(
    'container.build_hash' => 'Ns2Dboa',
    'container.build_id' => 'f94beba3',
    'container.build_time' => 1519028448,
));
