<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXx1Ddd7\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXx1Ddd7/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXx1Ddd7.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXx1Ddd7\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXx1Ddd7\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Xx1Ddd7',
    'container.build_id' => 'd683cf02',
    'container.build_time' => 1519825492,
));
