<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evento extends \App\Entity\Evento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'imagen', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'titulo', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'fk_provincia', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'direccion', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'fk_categoria', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'enlace_externo', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'descripcion', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'total_entradas', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'entradas_restantes', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'precio_entradas', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'venta_fecha_inicio', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'venta_fecha_fin', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'fecha_celebracion', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'hora_celebracion', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'fk_usuario'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'imagen', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'titulo', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'fk_provincia', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'direccion', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'fk_categoria', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'enlace_externo', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'descripcion', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'total_entradas', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'entradas_restantes', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'precio_entradas', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'venta_fecha_inicio', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'venta_fecha_fin', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'fecha_celebracion', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'hora_celebracion', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'fk_usuario'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Evento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getImagen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagen', []);

        return parent::getImagen();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagen($imagen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagen', [$imagen]);

        return parent::setImagen($imagen);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', []);

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', [$titulo]);

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkProvincia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkProvincia', []);

        return parent::getFkProvincia();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkProvincia($fk_provincia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkProvincia', [$fk_provincia]);

        return parent::setFkProvincia($fk_provincia);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', []);

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', [$direccion]);

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkCategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkCategoria', []);

        return parent::getFkCategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkCategoria($fk_categoria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkCategoria', [$fk_categoria]);

        return parent::setFkCategoria($fk_categoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnlaceExterno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnlaceExterno', []);

        return parent::getEnlaceExterno();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnlaceExterno($enlace_externo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnlaceExterno', [$enlace_externo]);

        return parent::setEnlaceExterno($enlace_externo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalEntradas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalEntradas', []);

        return parent::getTotalEntradas();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalEntradas($total_entradas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalEntradas', [$total_entradas]);

        return parent::setTotalEntradas($total_entradas);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntradasRestantes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntradasRestantes', []);

        return parent::getEntradasRestantes();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntradasRestantes($entradas_restantes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntradasRestantes', [$entradas_restantes]);

        return parent::setEntradasRestantes($entradas_restantes);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecioEntradas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecioEntradas', []);

        return parent::getPrecioEntradas();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecioEntradas($precio_entradas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecioEntradas', [$precio_entradas]);

        return parent::setPrecioEntradas($precio_entradas);
    }

    /**
     * {@inheritDoc}
     */
    public function getVentaFechaInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVentaFechaInicio', []);

        return parent::getVentaFechaInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setVentaFechaInicio($venta_fecha_inicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVentaFechaInicio', [$venta_fecha_inicio]);

        return parent::setVentaFechaInicio($venta_fecha_inicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getVentaFechaFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVentaFechaFin', []);

        return parent::getVentaFechaFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setVentaFechaFin($venta_fecha_fin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVentaFechaFin', [$venta_fecha_fin]);

        return parent::setVentaFechaFin($venta_fecha_fin);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCelebracion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCelebracion', []);

        return parent::getFechaCelebracion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCelebracion($fecha_celebracion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCelebracion', [$fecha_celebracion]);

        return parent::setFechaCelebracion($fecha_celebracion);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraCelebracion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraCelebracion', []);

        return parent::getHoraCelebracion();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraCelebracion($hora_celebracion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraCelebracion', [$hora_celebracion]);

        return parent::setHoraCelebracion($hora_celebracion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkUsuario', []);

        return parent::getFkUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkUsuario($fk_usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkUsuario', [$fk_usuario]);

        return parent::setFkUsuario($fk_usuario);
    }

}
